#!/usr/bin/env perl
# This extension adds a small handler to fork off a new urxvt window at the your working directory.
# 
# To install:
# 
# * copy `fork-here' anywhere to your liking
# * if necessary, add that path to `URxvt.perl-lib'
# * add `fork-here' to `URxvt.perl-ext'
# * bind something toi `perl:fork-here:fork-at-cwd'

sub on_child_start {
	my $shell = $_[1];
	$_[0]->{fork_here_shell} = $shell;
	()
}

sub on_user_command {
	if ($_[1] eq "fork-here:fork-at-cwd") {
		my $shell = $_[0]->{fork_here_shell};
		my $pwd = readlink("/proc/$shell/cwd");
		$_[0]->exec_async("urxvtc", "-cd", $pwd);
	}
	()
}
